language: bash
script:
- echo "$TRAVIS_COMMIT" | tee payload.txt
- cat payload.txt
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "payload.txt"
  skip_cleanup: true
  on:
    tags: true
    repo: mcspr/release-test
