on:
  release:
    types:
      - published
      
jobs:
  stuff:
    name: Doing stuff
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Prepare
      id: prepare
      run: |
        tag=""
        [[ "${GITHUB_REF}" =~ refs/tags/ ]] && {
          tag=$(echo "${GITHUB_REF}" | cut -c11-)
          echo "::set-output name=tag::${tag}"
        }
        test -n "$tag"
        echo "Tag is $tag"
    - name: Fetch some file
      env:
        GITHUB_TAG: ${{ steps.prepare.tag }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        curl --fail \
             --header "Accept: application/vnd.github.v3+json" \
             --header "Authorization: token ${GITHUB_TOKEN}" \
             "https://api.github.com/repos/${GITHUB_REPO}/contents/README.md?ref=${GITHUB_TAG}" \
          | jq -r '.contents' | base64 -d > README.md 
    - name: Show what we got
      env:
        GITHUB_TAG: ${{ steps.prepare.tag }}
      run: |
        tree
        cat README.md
        echo "Down here tag is ${GITHUB_TAG}"
