on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  stuff:
    name: Doing stuff
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Prepare
      id: prepare
      run: |
        tag=""
        [[ "${GITHUB_REF}" =~ refs/tags/ ]] && {
          tag=$(echo "${GITHUB_REF}" | cut -c11-)
          echo "::set-output name=tag::${tag}"
        }
        test -n "$tag"
        echo "Tag is $tag"
    - name: Fetch some file
      env:
        GITHUB_TAG: ${{ steps.prepare.outputs.tag }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        test -n "$GITHUB_TAG"
        test -n "$GITHUB_REPO"
        curl --silent --fail \
             --header "Accept: application/vnd.github.v3.raw" \
             --header "Authorization: token ${GITHUB_TOKEN}" \
             --output README.md \
             "https://api.github.com/repos/${GITHUB_REPO}/contents/README.md?ref=${GITHUB_TAG}"
    - name: Show what we got
      env:
        GITHUB_TAG: ${{ steps.prepare.outputs.tag }}
      run: |
        tree -h
        cat README.md
        echo "Down here tag is ${GITHUB_TAG}"
