on:
  push:

jobs:
  stuffs:
    name: Checking
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      run: |
        env
    - name: Do
      run: |
        echo "# This is a header" >> $GITHUB_STEP_SUMMARY
        echo "```cpp" >> $GITHUB_STEP_SUMMARY
        echo "void this_is_a_code_block();" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
